version: '3'

services:
  api:
    image: go-api
    command: /go/app/api
    ports:
      - 8081:8081
    networks:
      back:
        ipv4_address: 172.16.238.3
    links:
      - "db:db"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8081/api/health|| exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  db:
    image: go-db
    command: /go/app/go-db
    volumes:
      - ./database:/database
    ports:
      - 8082:8082
    networks:
      back:
        ipv4_address: 172.16.238.4
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8082/db/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  back:
    driver: bridge
    enable_ipv6: False
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
