version: '3.2'

services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    depends_on:
      - db
      - api
    networks:
      back:
        ipv4_address: 172.16.238.2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1234
  api:
    build:
      context: ./golang-api
      cache_from: 
        - rivee/golang-base-build-curl:latest
    environment:
      API_PORT: "8081"
    ports:
      - 8081
    networks:
      back:
        ipv4_address: 172.16.238.3
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8081/api/health|| exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  db:
    build:
      context: ./golang-db
      cache_from: 
        - rivee/golang-base-build-curl:latest
    environment:
      DB_PORT: "8082"
    volumes:
      - ./database:/database
    ports:
      - 8082
    networks:
      back:
        ipv4_address: 172.16.238.4
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8082/db/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  back:
    driver: bridge
    enable_ipv6: False
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
